analytics.onpremise.enable=false
analytics.integration.enable=true
analytics.project="{\\n  \\"id\\"\: 3409455,\\n  \\"name\\"\: \\"First Project\\",\\n  \\"teamId\\"\: 3381047,\\n  \\"organizationId\\"\: 3446010,\\n  \\"isSampleProject\\"\: false,\\n  \\"canAutoIntegrate\\"\: false\\n}"
analytics.team="{\\n  \\"id\\"\: 3381047\\n}"
analytics.testcloud.integration.enable=false
analytics.testreport.autoupload.enable=true
analytics.testcloud.hub.switchHub.enable=false
